### ISSUE TITLE
Generating snapshots doesn't work on Windows

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/mosaic#451]
After this commit: https://github.com/jpmorganchase/mosaic/commit/6511d7ca5516b58678cd0a36d2be54bf9032f5da generating snapshots doesn't work with mosaic and failed with:

```shell
@jpmorganchase/mosaic-site:serve: 8080 Error resolving ref(s) for page '/mosaic/author/aliases.mdx'. Error reading file "d:/mosaic/author/" in 'd:/mosaic/author/'
@jpmorganchase/mosaic-site:serve: 8080 Error: Error: Error: Plugin 'D:\Work\mosaic\packages\plugins\dist\$RefPlugin.js' threw an exception running `$beforeSend`. See below:
@jpmorganchase/mosaic-site:serve: 8080   JSONParserError: Error reading file "d:/mosaic/author/"
@jpmorganchase/mosaic-site:serve: 8080     at D:\Work\mosaic\node_modules\@apidevtools\json-schema-ref-parser\dist\lib\parse.js:109:23
@jpmorganchase/mosaic-site:serve: 8080     at Generator.throw (<anonymous>)
@jpmorganchase/mosaic-site:serve: 8080     at rejected (D:\Work\mosaic\node_modules\@apidevtools\json-schema-ref-parser\dist\lib\parse.js:29:65)
@jpmorganchase/mosaic-site:serve: 8080     at runNextTicks (node:internal/process/task_queues:60:5)
@jpmorganchase/mosaic-site:serve: 8080     at process.processImmediate (node:internal/timers:447:9)
@jpmorganchase/mosaic-site:serve: 8080     at Object.$beforeSend (file:///D:/Work/mosaic/packages/core/dist/plugin/index.js:66:23)
@jpmorganchase/mosaic-site:serve: 8080     at runNextTicks (node:internal/process/task_queues:60:5)
@jpmorganchase/mosaic-site:serve: 8080     at process.processImmediate (node:internal/timers:447:9)
@jpmorganchase/mosaic-site:serve: 8080     at async file:///D:/Work/mosaic/packages/core/dist/worker/Source.worker.js:38:9
@jpmorganchase/mosaic-site:serve: 8080 Error: [Mosaic] Source 'site#c05241dc' threw an exception. See below:
@jpmorganchase/mosaic-site:serve: 8080     at EventEmitter.<anonymous> (file:///D:/Work/mosaic/packages/core/dist/PullDocs.js:81:27)
@jpmorganchase/mosaic-site:serve: 8080     at Object.onceWrapper (node:events:629:26)
@jpmorganchase/mosaic-site:serve: 8080     at EventEmitter.emit (node:events:526:35)
@jpmorganchase/mosaic-site:serve: 8080     at file:///D:/Work/mosaic/packages/core/dist/Source.js:124:57
@jpmorganchase/mosaic-site:serve: 8080     at EventEmitter.autoUnsubscribeHandler (file:///D:/Work/mosaic/packages/core/dist/WorkerSubscription.js:34:13)
@jpmorganchase/mosaic-site:serve: 8080     at EventEmitter.emit (node:events:514:28)
@jpmorganchase/mosaic-site:serve: 8080     at #onError [as error] (file:///D:/Work/mosaic/packages/core/dist/WorkerSubscription.js:61:23)
@jpmorganchase/mosaic-site:serve: 8080     at ConsumerObserver.error (D:\Work\mosaic\node_modules\rxjs\dist\cjs\internal\Subscriber.js:124:33)
@jpmorganchase/mosaic-site:serve: 8080     at Subscriber._error (D:\Work\mosaic\node_modules\rxjs\dist\cjs\internal\Subscriber.js:84:30)
@jpmorganchase/mosaic-site:serve: 8080     at Subscriber.error (D:\Work\mosaic\node_modules\rxjs\dist\cjs\internal\Subscriber.js:60:18)
@jpmorganchase/mosaic-site:serve: 8080 [Mosaic] Source 'site#c05241dc' closed

```

**Comment by DavieReid** [comment]
I think this is caused by the ref parser lib appending the drive letter on Windows.  Looking at a fix...
